SimpleBlog.WebApp/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using SimpleBlog.Model;
using SimpleBlog.Service;
using SimpleBlog.WebApp.ViewModels;

namespace SimpleBlog.WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly IPostService _postService;
        private readonly ICommentService _commentService;

        public HomeController(IPostService postService, ICommentService commentService)
        {
            _postService = postService;
            _commentService = commentService;
        }

        public ActionResult Index()
        {
            IEnumerable<PostViewModel> viewModelBlog;
            IEnumerable<Post> posts;

            posts = _postService.GetPosts().OrderByDescending(p => p.Date);

            viewModelBlog = Mapper.Map<IEnumerable<Post>, IEnumerable<PostViewModel>>(posts);
            return View(viewModelBlog);
        }
    }
}

SimpleBlog.WebApp/Controllers/PostController.cs
using System;
using System.Net;
using System.Web.Mvc;
using AutoMapper;
using Microsoft.AspNet.Identity;
using SimpleBlog.Model;
using SimpleBlog.Service;
using SimpleBlog.WebApp.ViewModels;

namespace SimpleBlog.WebApp.Controllers
{
    [Authorize]
    public class PostController : Controller
    {
        private readonly IPostService _postService;

        public PostController(IPostService postService)
        {
            _postService = postService;
        }

        // GET: Post/Create
        public ActionResult Create()
        {
            return View();
        }

        // GET: Post/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create(PostViewModel model)
        {
            if (ModelState.IsValid)
            {
                Post post = new Post
                {
                    Title = model.Title,
                    Text = model.Text,
                    Date = DateTime.Now,
                    AuthorId = User.Identity.GetUserId()
                };
                _postService.CreatePost(post);
                _postService.SavePost();

                return RedirectToAction("Index", "Home");
            }

            return View(model);    
        }

        // GET: Post/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            PostViewModel viewModelPost;
            Post post;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                post = _postService.GetPost(id.Value);
            }
            if (post == null)
            {
                return HttpNotFound();
            }
            viewModelPost = Mapper.Map<Post, PostViewModel>(post);
            return View(viewModelPost);
        }
    }
}

SimpleBlog.WebApp/Views/Home/Index.cshtml
@model IEnumerable<SimpleBlog.WebApp.ViewModels.PostViewModel>

@{
    ViewBag.Title = "Home Page";
}

<div class="row" style="margin-top: 32px">
    @{var last = Model.Last();}
    @foreach (var item in Model)
    {
        <div class="col-lg-12">
            <div class="row">
                <div class="col-sm-9">
                    <h3 class="pull-left" style="margin-top: 0px;">
                        <a href="@Url.Action("Details", "Post", new {id = item .Id})">@item.Title</a>
                    </h3>
                </div>
                <div class="col-sm-3">
                    <h5 class="pull-right" style="margin-top: 0px;">
                        <i class="fa fa-calendar"></i> Posted on @item.Date
                    </h5>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <i class="fa fa-user" style="margin-bottom: 7px;"></i> <em>by @{ Html.RenderAction("GetUserNameById", "Account", new { appUserId = item.AuthorId });}</em>
                </div>
            </div>
            @Html.Raw(item.Text)
            <div class="row" style="margin-top: 16px">
                <div class="col-lg-12">
                    <span>
                        <i class="glyphicon glyphicon-comment"></i>
                        <a href="@Url.Action("Details", "Post", new {id = item .Id})#comments">
                            @if (item.Comments.Count > 0)
                            {
                                string c = item.Comments.Count > 1 ? "comments" : "comment";
                                @Html.Raw($"{item.Comments.Count} {c}")
                            }
                            else
                            {
                                @Html.Raw("comment on this")
                            }
                        </a>
                    </span>
                </div>
            </div>
            @if (!item.Equals(last))
            {
                <hr />
            }
        </div>
    }
</div>