SimpleBlog.WebApp/ViewModels/PostViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SimpleBlog.WebApp.ViewModels
{
    public class PostViewModel
    {
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Text { get; set; }

        public DateTime Date { get; set; }

        public string AuthorId { get; set; }

        public ICollection<CommentViewModel> Comments { get; set; }
    }
}

SimpleBlog.WebApp/Controllers/CommentController.cs
using System;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using SimpleBlog.Model;
using SimpleBlog.Service;

namespace SimpleBlog.WebApp.Controllers
{
    [Authorize]
    public class CommentController : Controller
    {
        private readonly ICommentService _commentService;

        public CommentController(ICommentService commentService)
        {
            _commentService = commentService;
        }

        // POST: Comment/Save
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Save(int postId, string commentText)
        {
            Comment comment = new Comment
            {
                PostId = postId,
                Date = DateTime.Now,
                AuthorId = User.Identity.GetUserId(),
                Text = commentText
            };
            _commentService.CreateComment(comment);
            _commentService.SaveComment();

            return RedirectToAction("Details", "Post", new { id = postId });
        }
    }
}

SimpleBlog.WebApp/Controllers/PostController.cs
using System;
using System.Net;
using System.Web.Mvc;
using AutoMapper;
using Microsoft.AspNet.Identity;
using SimpleBlog.Model;
using SimpleBlog.Service;
using SimpleBlog.WebApp.ViewModels;

namespace SimpleBlog.WebApp.Controllers
{
    [Authorize]
    public class PostController : Controller
    {
        private readonly IPostService _postService;

        public PostController(IPostService postService)
        {
            _postService = postService;
        }

        // GET: Post/Create
        public ActionResult Create()
        {
            return View();
        }

        // GET: Post/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create(PostViewModel model)
        {
            if (ModelState.IsValid)
            {
                Post post = new Post
                {
                    Title = model.Title,
                    Text = model.Text,
                    Date = DateTime.Now,
                    AuthorId = User.Identity.GetUserId()
                };
                _postService.CreatePost(post);
                _postService.SavePost();

                return RedirectToAction("Index", "Home");
            }

            return View(model);    
        }

        // GET: Post/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            PostViewModel viewModelPost;
            Post post;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                post = _postService.GetPost(id.Value);
            }
            if (post == null)
            {
                return HttpNotFound();
            }
            viewModelPost = Mapper.Map<Post, PostViewModel>(post);
            return View(viewModelPost);
        }
    }
}

SimpleBlog.WebApp/Views/Post/Create.cshtml
@model SimpleBlog.WebApp.ViewModels.PostViewModel

@{
    ViewBag.Title = "Create post";
}

@using (Html.BeginForm()) //"Save", "Post", null, FormMethod.Post, new { role = "form" })
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>New post</h4>
        <hr/>
        @Html.ValidationSummary("", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, "Title", htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new {htmlAttributes = new {@class = "form-control", style = "width: 100%; max-width: 100%;" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Text, "Text of the post", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Text, new { @class = "form-control", rows = "25", style = "width: 100%; max-width: 100%;" } )
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-primary"><i class="fa fa-reply"></i> Submit</button>
            </div>
        </div>
    </div>
}

SimpleBlog.WebApp/Views/Post/Details.cshtml
@model SimpleBlog.WebApp.ViewModels.PostViewModel

@{
    ViewBag.Title = "Post Details";
}

<div class="row" style="margin-top: 32px">
    <div class="col-lg-12">
        <div class="row">
            <div class="col-sm-9">
                <h3 class="pull-left" style="margin-top: 0px;">
                    <a href="">@Model.Title</a>
                </h3>
            </div>
            <div class="col-sm-3">
                <h5 class="pull-right" style="margin-top: 0px;">
                    <i class="fa fa-calendar"></i> Posted on @Model.Date
                </h5>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <i class="fa fa-user" style="margin-bottom: 7px;"></i> <em>by @{ Html.RenderAction("GetUserNameById", "Account", new {appUserId = Model.AuthorId});}</em>
            </div>
        </div>

        @Html.Raw(Model.Text)

        <a href="#comments"></a>
        <div class="row" style="margin-top: 16px">
            <div class="col-sm-12">
                @if (Request.IsAuthenticated)
                {
                    <hr />
                    <div class="well">
                        <h4><i class="fa fa-paper-plane-o"></i> Leave a Comment:</h4>
                        @using (Html.BeginForm("Save", "Comment", new { postId = Model.Id }, FormMethod.Post, new { role = "form" }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary("", new { @class = "text-danger" })
                            <div class="form-group">
                                @Html.TextArea("commentText", null, new { @class = "form-control", rows = "4", style = "width: 100%; max-width: 100%;" })
                            </div>
                            <button type="submit" class="btn btn-primary"><i class="fa fa-reply"></i> Submit</button>
                        }
                    </div>
                }              
                @foreach (var comment in Model.Comments)
                {
                    <h4>
                        <i class="fa fa-comment"></i> @{ Html.RenderAction("GetUserNameById", "Account", new {appUserId = comment.AuthorId}); } says:
                        <small> on @comment.Date</small>
                    </h4>
                    <p>@Html.Raw(comment.Text)</p>
                }
            </div>
        </div>
    </div>

</div>